run:
  timeout: 5m
  go: "1.24"

# This is the version of golangci-lint configuration
version: 2

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - godot
    - revive
    - whitespace

# Formatters (not linters)
formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  stylecheck:
    checks: ["all", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - goconst
    - path: integration/
      linters:
        - gocyclo
        - dupl
        - goconst
    - path: pypi/client\.go
      linters:
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0 