apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: prefetch-dependencies-tejedor-example
spec:
  taskRef:
    name: prefetch-dependencies-tejedor
  params:
    - name: input
      value: "pip"
    - name: private-pypi-url
      value: "https://private-pypi.company.com/simple/"
    - name: proxy-server
      value: "http://proxy.company.com:8080"
    - name: log-level
      value: "debug"
    - name: dev-package-managers
      value: "false"
    - name: sbom-type
      value: "spdx"
    - name: config-file-content
      value: |
        ---
        requests_timeout: 300
        subprocess_timeout: 3600
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: source-pvc
    - name: git-basic-auth
      secret:
        secretName: git-credentials
    - name: netrc
      secret:
        secretName: netrc-credentials 